-- ============================================================
-- RETIRED. This used to create superadmin@ / pos@ / driver@ staff
-- logins with a hard-coded password — and because it used
-- ON CONFLICT ... DO UPDATE, re-running it RESET those accounts'
-- passwords back to that published value. It was already applied to
-- production, so the version stays (migration history lines up) but
-- the body is now a no-op. Create staff through Admin → Staff instead:
-- the invite email makes them set their own password, and it links
-- their branch.
-- ============================================================
SELECT 1;
